use std::path::Path;

#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum Language {
    Json,
    JavaScript,
    TypeScript,
    Jsx,
    Tsx,
    Go,
    Rust,
    Swift,
    Kotlin,
    Java,
    PlainText,
}

impl Language {
    pub fn from_path(path: &Path) -> Option<Self> {
        let ext = path.extension()?.to_str()?.to_ascii_lowercase();
        match ext.as_str() {
            "json" => Some(Self::Json),
            "js" | "mjs" | "cjs" => Some(Self::JavaScript),
            "ts" => Some(Self::TypeScript),
            "jsx" => Some(Self::Jsx),
            "tsx" => Some(Self::Tsx),
            "go" => Some(Self::Go),
            "rs" => Some(Self::Rust),
            "swift" => Some(Self::Swift),
            "kt" | "kts" => Some(Self::Kotlin),
            "java" => Some(Self::Java),
            _ => None,
        }
    }

    pub fn infer_from_content(content: &str) -> Self {
        let trimmed = content.trim_start();
        if trimmed.starts_with('{') || trimmed.starts_with('[') {
            Self::Json
        } else {
            Self::PlainText
        }
    }

    pub fn keywords(self) -> &'static [&'static str] {
        match self {
            Self::Json | Self::PlainText => &[],
            Self::JavaScript | Self::Jsx => &[
                "async",
                "await",
                "break",
                "case",
                "catch",
                "class",
                "const",
                "continue",
                "default",
                "delete",
                "do",
                "else",
                "export",
                "extends",
                "false",
                "finally",
                "for",
                "from",
                "function",
                "if",
                "import",
                "in",
                "let",
                "new",
                "null",
                "of",
                "return",
                "static",
                "super",
                "switch",
                "this",
                "throw",
                "true",
                "try",
                "typeof",
                "undefined",
                "var",
                "while",
                "yield",
            ],
            Self::TypeScript | Self::Tsx => &[
                "abstract",
                "any",
                "as",
                "async",
                "await",
                "boolean",
                "break",
                "case",
                "catch",
                "class",
                "const",
                "continue",
                "declare",
                "default",
                "else",
                "enum",
                "export",
                "extends",
                "false",
                "finally",
                "for",
                "from",
                "function",
                "if",
                "implements",
                "import",
                "interface",
                "let",
                "module",
                "namespace",
                "never",
                "new",
                "null",
                "number",
                "private",
                "protected",
                "public",
                "readonly",
                "return",
                "static",
                "string",
                "super",
                "switch",
                "this",
                "throw",
                "true",
                "try",
                "type",
                "typeof",
                "undefined",
                "unknown",
                "var",
                "void",
                "while",
            ],
            Self::Go => &[
                "break",
                "case",
                "chan",
                "const",
                "continue",
                "default",
                "defer",
                "else",
                "fallthrough",
                "for",
                "func",
                "go",
                "goto",
                "if",
                "import",
                "interface",
                "map",
                "nil",
                "package",
                "range",
                "return",
                "select",
                "struct",
                "switch",
                "type",
                "var",
            ],
            Self::Rust => &[
                "as", "async", "await", "break", "const", "continue", "crate", "dyn", "else",
                "enum", "extern", "false", "fn", "for", "if", "impl", "in", "let", "loop", "match",
                "mod", "move", "mut", "pub", "ref", "return", "self", "Self", "static", "struct",
                "super", "trait", "true", "type", "unsafe", "use", "where", "while",
            ],
            Self::Swift => &[
                "as",
                "associatedtype",
                "break",
                "case",
                "catch",
                "class",
                "continue",
                "default",
                "defer",
                "do",
                "else",
                "enum",
                "extension",
                "false",
                "for",
                "func",
                "guard",
                "if",
                "import",
                "in",
                "init",
                "let",
                "nil",
                "private",
                "protocol",
                "public",
                "return",
                "self",
                "static",
                "struct",
                "switch",
                "throw",
                "throws",
                "true",
                "try",
                "typealias",
                "var",
                "where",
                "while",
            ],
            Self::Kotlin => &[
                "as",
                "break",
                "class",
                "continue",
                "data",
                "do",
                "else",
                "false",
                "for",
                "fun",
                "if",
                "import",
                "in",
                "interface",
                "is",
                "null",
                "object",
                "package",
                "private",
                "protected",
                "public",
                "return",
                "sealed",
                "super",
                "this",
                "throw",
                "true",
                "try",
                "typealias",
                "val",
                "var",
                "when",
                "while",
            ],
            Self::Java => &[
                "abstract",
                "assert",
                "boolean",
                "break",
                "byte",
                "case",
                "catch",
                "char",
                "class",
                "const",
                "continue",
                "default",
                "do",
                "double",
                "else",
                "enum",
                "extends",
                "false",
                "final",
                "finally",
                "float",
                "for",
                "if",
                "implements",
                "import",
                "instanceof",
                "int",
                "interface",
                "long",
                "new",
                "null",
                "package",
                "private",
                "protected",
                "public",
                "return",
                "short",
                "static",
                "strictfp",
                "super",
                "switch",
                "this",
                "throw",
                "throws",
                "true",
                "try",
                "void",
                "while",
            ],
        }
    }
}

#[cfg(test)]
mod tests {
    use super::Language;
    use std::path::Path;

    #[test]
    fn detects_supported_languages() {
        assert_eq!(
            Language::from_path(Path::new("main.rs")),
            Some(Language::Rust)
        );
        assert_eq!(
            Language::from_path(Path::new("app.tsx")),
            Some(Language::Tsx)
        );
        assert_eq!(
            Language::from_path(Path::new("build.gradle.kts")),
            Some(Language::Kotlin)
        );
        assert_eq!(Language::from_path(Path::new("notes.txt")), None);
    }

    #[test]
    fn infers_json_from_content() {
        assert_eq!(
            Language::infer_from_content("{\"ok\": true}"),
            Language::Json
        );
        assert_eq!(
            Language::infer_from_content("plain text"),
            Language::PlainText
        );
    }
}
